word = "gzog6zilzq6zxlt"
hasChosenLineReport = true
tripleQuestionMarkInessentiel = 1000
npcFinderThingMaxDistanceChangeBeforeCacheInvalid = 0.5
playAllSoundsOnPlayer = false
reportMissingLines = false
anonymous = false
sendFunFact = false
blockCutOff = 32
highlightSpeaker = false
logDialogueLines = true
onlyLogNotPlayingLines = true
logPlayingInformation = false
